### ISSUE TITLE
NPM Package

### ISSUE THREAD

**Issue by emiliekmartinez** [thetrevorharmon/gatsby-theme-shopify-manager#22]
Looks like you scope/init NPM packages to a specific folder. So in our usecase we'll just scope it to the project folder. See [Step #5 > "user scoped"](https://docs.npmjs.com/creating-and-publishing-scoped-public-packages).

**Comment by thetrevorharmon** [comment]
Hmmm this looks like it's around scoping packages according to the organization they are a part of but not according to the folder structure (i.e. if it's scoped to`@shopify`, then you reference the package like `@shopify/some-package`. This is really common with `@types/*` packages). 

An example of a npm module that is a subdirectory of a monorepo is `gatsby-image`: https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-image (and also https://www.npmjs.com/package/gatsby-image)
