### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by balibebas** [thetrevorharmon/gatsby-theme-shopify-manager#64]
I noticed there's no license. How are you planning to license this code?

**Comment by thetrevorharmon** [comment]
Oops! I meant to add an MIT license to this. Want to open a PR?

**Comment by balibebas** [comment]
I'm on really slow internet right now. This might be easier: https://github.com/thetrevorharmon/gatsby-theme-shopify-manager/community/license/new?template=MIT

**Comment by balibebas** [comment]
I dropped in your name Trevor but given this work may have been completed under an employment contract please be sure to clear it with the VP of Tech before merging my PR. Thanks.

**Comment by thetrevorharmon** [comment]
It’s an entirely self-created piece of software (not at at all sponsored), so the license you added looks right.

**Comment by balibebas** [comment]
And a splendid piece of software at that. Thanks so much, Trevor.
