### ISSUE TITLE
How to expose Metafields in the the theme

### ISSUE THREAD

**Issue by adinjesuha** [thetrevorharmon/gatsby-theme-shopify-manager#79]
Hi bro... greate work with this theme.

I need to know how to implement custom configuration in the gatsby-source-shopify plugin directly from the theme, your theme doesn't have options to do that. Or I missing something??

Thanks for your helpe with this!

**Comment by thetrevorharmon** [comment]
Hi there, what version are you on? On `0.1.18`, it requires you to install `gatsby-source-shopify` separately, and you'll be able to do all the config you need to do on that

**Comment by thetrevorharmon** [comment]
You'll also need to pass `shouldConfigureSourcePlugin: false` to the theme options (forgot to mention that)

**Comment by adinjesuha** [comment]
Thanks man, just make `shouldConfigureSourcePlugin: true` and expose the metafields via storefront api...

**Comment by thetrevorharmon** [comment]
@adinjesuha I think your issue is probably solved; reopen this if you are still facing the issue
