### ISSUE TITLE
Digital Products?

### ISSUE THREAD

**Issue by madebylance** [thetrevorharmon/gatsby-theme-shopify-manager#81]
I am creating a store that has only digital products. How can I process that through Gatsby and Shopify?

**Comment by thetrevorharmon** [comment]
That is a big question that is outside of the scope of this repo. I would start by looking at [this blog post](https://www.shopify.com/blog/digital-products) on Shopify's website, and then look into how to build a Shopify store on Gatsby. Good luck.
