### ISSUE TITLE
Multiple Shopify stores?

### ISSUE THREAD

**Issue by davidpaulsson** [thetrevorharmon/gatsby-theme-shopify-manager#89]
First off: thanks for a great plugin!

I'm wondering what's the best approach would be to build a regionalized gatsby site that connects to different Shopify stores? My company currently have different Shopify stores for different regions, like one Shopify store for US, one for EU, one for Canada etc.

I'm trying to figure out the architecture for this to have `mysite.com/en-eu/:splat`, `mysite.com/en-us/:splat`, and `mysite.com/en-ca/:splat`, etc, and have `useCart` (as an example) connect to the different Shopify stores based on a regional setting. Is it possible to somehow have multiple versions of gatsby-theme-shopify-manager running at once?

**Comment by thetrevorharmon** [comment]
I would pass `false` to `shouldWrapRootElementWithProvider` ([docs link](https://gatsbythemeshopifymanager.com/#shouldwraprootelementwithprovider)). From there, you can set up your own [context provider](https://gatsbythemeshopifymanager.com/#contextprovider) that conditionally provides the right access token/info.

Example:
```
import React from 'react';
import {ContextProvider} from 'gatsby-theme-shopify-manager';
export function StoreWrapper = ({children}) => {
  
  const shopName = {
    us: 'some-US-shop-name',
    eu: 'some-EU-shop-name',
  };
  
  const accessToken = {
    us: 'some-US-token',
    eu: 'some-EU-token',
  };

  return (
    <ContextProvider shopName={shopName[currentLocation]} accessToken={accessToken[currentLocation]}>
      {children}
    </ContextProvider>
  );
};
```
I _think_ this will work, but I've never tried something like this. Best of luck.

**Comment by davidpaulsson** [comment]
@thetrevorharmon Thank you!
